//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <unistd.h>

// ------------------- Function Prototypes --------------------

int32_t print(int32_t * buf);
int32_t strlen(char * a1);

// ------------------------ Functions -------------------------

// Address range: 0x80480c6 - 0x80480ec
int32_t strlen(char * a1) {
    // 0x80480c6
    if (*a1 == 0) {
        // 0x80480e7
        return 0;
    }
    int32_t v1 = (int32_t)a1 + 1; // 0x80480d5
    int32_t result = 1; // 0x80480d9
    // branch -> 0x80480d5
    while (*(char *)v1 != 0) {
        // 0x80480d5
        v1++;
        result++;
        // continue -> 0x80480d5
    }
    // 0x80480e7
    return result;
}

// Address range: 0x80480ec - 0x8048116
int32_t print(int32_t * buf) {
    // 0x80480ec
    return write(1, buf, strlen((char *)buf));
}

// Address range: 0x8048116 - 0x804812d
int main(int argc, char ** argv) {
    // 0x8048116
    print((int32_t *)"Hello, world!\n");
    return 0;
}

// ------------------ System-Call Functions -------------------

// ssize_t write(int fd, const void * buf, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 3
// Decompilation date: 2018-06-08 21:49:33
