//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

void _start(int32_t status);
int32_t add(int32_t a1, int32_t a2);
int32_t head(int32_t * a1);

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x100d
int32_t add(int32_t a1, int32_t a2) {
    // 0x1000
    return a2 + a1;
}

// Address range: 0x100d - 0x1017
int32_t head(int32_t * a1) {
    // 0x100d
    return *a1;
}

// Address range: 0x1017 - 0x107b
int main(int argc, char ** argv) {
    int32_t v1 = 1; // bp-16
    int32_t v2 = 4; // bp-32
    int32_t v3 = 8; // bp-36
    head(&v2);
    head(&v3);
    return head(&v1);
}

// Address range: 0x107b - 0x1089
void _start(int32_t status) {
    // 0x107b
    int32_t * v1;
    main((int32_t)&v1, (char **)&v1);
    exit(0);
}

// ------------------ System-Call Functions -------------------

// void exit(int status);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (8.2.1)
// Detected functions: 4
// Decompilation date: 2018-09-19 16:35:54
