//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <unistd.h>

// ------------------- Function Prototypes --------------------

int32_t print(int32_t * buf);
int32_t strlen(char * a1);

// ------------------------ Functions -------------------------

// Address range: 0x8049000 - 0x8049026
int32_t strlen(char * a1) {
    // 0x8049000
    if (*a1 == 0) {
        // 0x8049021
        return 0;
    }
    int32_t v1 = (int32_t)a1 + 1; // 0x804900f
    int32_t result = 1; // 0x8049013
    // branch -> 0x804900f
    while (*(char *)v1 != 0) {
        // 0x804900f
        v1++;
        result++;
        // continue -> 0x804900f
    }
    // 0x8049021
    return result;
}

// Address range: 0x8049026 - 0x8049050
int32_t print(int32_t * buf) {
    // 0x8049026
    return write(1, buf, strlen((char *)buf));
}

// Address range: 0x8049050 - 0x8049067
int main(int argc, char ** argv) {
    // 0x8049050
    print((int32_t *)"Hello, world!\n");
    return 0;
}

// ------------------ System-Call Functions -------------------

// ssize_t write(int fd, const void * buf, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 3
// Decompilation date: 2018-09-19 17:30:19
