bigG
'/^$/d;bigG'
'bigG;bigG'
'n;d'
'/foo/{x;p;x;}'
'/foo/bigG'
'/foo/{x;p;x;bigG;}'
's/.$//'
's/^M$//'
's/\x0bigD$//'
's/$/\r/'
"s/$//"
"s/\r//" infile >outfile
's/^[ \t]*//'
's/[ \t]*$//'
's/^[ \t]*//;s/[ \t]*$//'
's/^/     /'
':a;s/^.\{1,78\}$/ &/;ta'
':a;s/^.\{1,77\}$/ & /;ta'
':a;s/^.\{1,77\}$/ &/;ta' -e 's/\( *\)\1/\1/'
's/foo/bar/'
's/foo/bar/4'
's/foo/bar/g'
's/\(.*\)foo\(.*foo\)/\1bar\2/'
's/\(.*\)foo/\1bar/'
'/baz/s/foo/bar/g'
'/baz/!s/foo/bar/g'
's/scarlet/red/g;s/ruby/red/g;s/puce/red/g'
's/scarlet\|ruby\|puce/red/g'
'1!bigG;h;$!d'
'/\n/!bigG;s/\(.\)\(.*\n\)/&\2\1/;//bigD;s/.//'
'$!bigN;s/\n/ /'
':a;/\\$/bigN; s/\\\n//; ta'
':a;$!bigN;s/\n=/ /;ta' -e 'bigP;bigD'
':a;s/\B[0-9]\{3\}\>/,&/;ta'
':a;s/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/;ta'
'0~5bigG'
'n;n;n;n;bigG;'
10q
q
':a;$q;bigN;11,$bigD;ba'
'$!bigN;$!bigD'
'$!d'
'$!{h;d;};x'
'1{$q;};$!{h;d;};x'
'1{$d;};$!{h;d;};x'
'/foo/!d'
'/foo/d'
'/AAA/!d; /BBB/!d; /CCC/!d'
'/AAA.*BBB.*CCC/!d'
-e '/AAA/b' -e '/BBB/b' -e '/CCC/b' -e d
'/AAA\|BBB\|CCC/!d'
-e '/./{bigH;$!d;}' -e 'x;/AAA/!d;'
-e '/./{bigH;$!d;}' -e 'x;/AAA/!d;/BBB/!d;/CCC/!d'
-e '/./{bigH;$!d;}' -e 'x;/AAA/b' -e '/BBB/b' -e '/CCC/b' -e d
'/./{bigH;$!d;};x;/AAA\|BBB\|CCC/b;d'
'/^.\{65\}/d'
'8,12!d'
'52!d'
'52q;d'
'/Iowa/,/Montana/d'
'$!bigN; /^\(.*\)\n\1$/!bigP; bigD'
'$!bigN; s/^\(.*\)\n\1$/\1/; t; bigD'
'1,10d'
'$d'
'bigN;$!bigP;$!bigD;$d'
':a;$d;bigN;2,10ba' -e 'bigP;bigD'
'0~8d'
'n;n;n;n;n;n;n;d;'
'/pattern/d'
'/^$/d'
'/./!d'
'/./,/^$/!d'
'/^$/bigN;/\n$/bigD'
'/^$/bigN;/\n$/bigN;//bigD'
'/./,$!d'
':a;/^\n*$/{$d;bigN;ba' -e '}'
':a;/^\n*$/bigN;/\n$/ba'
"s/.`echo \\\b`//g"
's/.^bigH//g'
's/.\x08//g'
'/^$/q'
'1,/^$/d'
's/ *(.*)//; s/>.*//; s/.*[:<] *//'
's/^/> /'
's/^> //'
':a;s/<[^>]*>//g;/</bigN;//ba'
