//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_ax(void);
void _start(int32_t status);

// ------------------------ Functions -------------------------

// Address range: 0x1b5 - 0x1c5
int main(int argc, char ** argv) {
    // 0x1b5
    __x86_get_pc_thunk_ax();
    return 5;
}

// Address range: 0x1c5 - 0x1c9
int32_t __x86_get_pc_thunk_ax(void) {
    // 0x1c5
    int32_t result;
    return result;
}

// Address range: 0x1c9 - 0x1d7
void _start(int32_t status) {
    // 0x1c9
    int32_t * v1;
    main((int32_t)&v1, (char **)&v1);
    exit(0);
}

// ------------------ System-Call Functions -------------------

// void exit(int status);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (8.1.1)
// Detected functions: 3
// Decompilation date: 2018-06-08 22:10:43
